# See https://pre-pre-commit --versioncommit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: python
        pass_filenames: false
        entry: isort --settings-path=saas/pyproject.toml saas
      - id: black
        name: black
        language: python
        pass_filenames: false
        entry: black --config=saas/pyproject.toml saas
      - id: flake8
        name: flak8
        language: python
        pass_filenames: false
        entry: pflake8 --config=saas/pyproject.toml saas
      - id: mypy
        name: mypy
        language: python
        pass_filenames: false
        entry: mypy --config-file=saas/pyproject.toml saas
      - id: pytest
        name: pytest
        language: python
        pass_filenames: false
        entry: pytest -c saas/pyproject.toml saas
      - id: poetry-export
        name: poetry-export
        description: run poetry export to sync lock file with requirements.txt
        entry: bash -c "cd saas && poetry export -f requirements.txt --output requirements.txt --without-hashes"
        language: python
        language_version: python3
        pass_filenames: false
        files: ^.*/poetry.lock$
      - id: poetry-export-dev
        name: poetry-export-dev
        description: run poetry export to sync lock file with requirements_dev.txt
        entry: bash -c "cd saas && poetry export --dev -f requirements.txt --output requirements_dev.txt --without-hashes"
        language: python
        language_version: python3
        pass_filenames: false
        files: ^.*/poetry.lock$
